### ISSUE TITLE
Failing docker run: "The command could not be loaded"

### ISSUE THREAD

**Issue by BenjaminEngeset** [TheCloudTheory/arm-estimator#179]
Hi!

Trying to take advantage of the tool, but facing some issue I have not been able to solve.

Tried with both `Ubuntu 22.04` and `20.04` Microsoft-hosted agent.

Tried with both `latest` and `1.1-beta2`.

```jobs:
- job: Main
  displayName: Run deployment test
  pool:
    vmImage: ubuntu-22.04
  steps:
  - checkout: self
    fetchDepth: 0

  - task: Bash@3
    displayName: Cost forecasting
    inputs:
      targetType: inline
      script: |
        docker run -e AZURE_CLIENT_ID=$(ClientId) -e AZURE_TENANT_ID=$(TenantId) -e AZURE_CLIENT_SECRET=$(Secret) -v /modules:/app thecloudtheory/azure-cost-estimator:1.1-beta2 modules/sql/servers/test/main.test.bicep $(SubscriptionId) $(ResourceGroupName)
```
Result emitted:

```
Status: Downloaded newer image for thecloudtheory/azure-cost-estimator:1.1-beta2
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'arm-estimator.dll' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
##[error]Bash exited with code '145'.
Finishing: Cost forecasting
```
Truly grateful for all help!

**Comment by kamil-mrzyglod** [comment]
Hey @BenjaminEngeset, thanks for reporting that!

I must say, that I sort of neglected Docker recently and I'm aware of that issue. I should be able to take a look this week and publish a fix for that.

The issue is related to the volume mapping, which overrides working directory when container is run. I'll prepare a working example on my end and publish it soon :)

**Comment by BenjaminEngeset** [comment]
> Hey @BenjaminEngeset, thanks for reporting that!
> 
> I must say, that I sort of neglected Docker recently and I'm aware of that issue. I should be able to take a look this week and publish a fix for that.
> 
> The issue is related to the volume mapping, which overrides working directory when container is run. I'll prepare a working example on my end and publish it soon :)

Great, looking forward to that!

**Comment by BenjaminEngeset** [comment]
@kamil-mrzyglod 

Am I a rude human being for bumping this one now?

Thanks in advance :)

**Comment by kamil-mrzyglod** [comment]
@BenjaminEngeset Sorry, being on vacation this month, sometimes I have difficulties finding stable internet connection :) Will try to check that today.

**Comment by kamil-mrzyglod** [comment]
Hey @BenjaminEngeset, sorry I kept you waiting. I pushed the latest tags once again but the actual issue is in the command itself (which I believe is caused by misleading documentation). 

An example ADO job could look like this:
```
job: Main
  displayName: Run deployment test
  pool:
    vmImage: ubuntu-22.04
  steps:
  - checkout: self
    fetchDepth: 0

  - task: Bash@3
    displayName: Cost forecasting
    inputs:
      targetType: inline
      script: |
        docker run -e AZURE_CLIENT_ID=$(Client_Id) -e AZURE_TENANT_ID=$(Tenant_Id) -e AZURE_CLIENT_SECRET=$(Client_Secret) -v $(pwd)/templates:/app/templates thecloudtheory/azure-cost-estimator templates/acr.bicep <subscription-id> <resource-group-name>
```

Note, that local template is mounted via `-v $(pwd)/templates:/app/templates`. There're two important things here:
- If you don't provide an absolute path for host path, Docker will create a named volume, which won't be connect to a host directory. Provide a full path so a bind mount is created instead.
- You need to map local directory to `/app/<your-directory>` instead of `/app` as `/app` is a working directory where ACE run within a container. Hence using `/app` will overwrite all the binaries and dotnet won't be able to find an executable.

One more thing - you don't need to use `-v` - you can also use `--mount` as the result will be the same. Let me know if that solves your issue.
