### ISSUE TITLE
Using ACE when Bicep modules are stored within a private container registry

### ISSUE THREAD

**Issue by BenjaminEngeset** [TheCloudTheory/arm-estimator#197]
Bicep has the potensial to store modules within a private module registry.

https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/modules#private-module-registry

However, in order for ACE to restore, authentication is needed with suffcient permission.

https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-cli#restore

How could we make this work?

**Comment by kamil-mrzyglod** [comment]
Hey @BenjaminEngeset!

If I understand that correctly, to restore modules from private module registry, the principal used in ACE needs to have sufficient permissions to do that. That should be a matter of using proper RBAC role for it and is outside of ACE's scope (one thing that could be added is support for passing Bicep config file).

However, what ACE doesn't support today, is running `bicep restore <bicep-file>` before compiling Bicep to ARM Templates, so remote modules are downloaded. That's something I can plan for `1.3`, so most likely would be available in `1.3-beta1` version within two weeks.

**Comment by kamil-mrzyglod** [comment]
I checked docs one more time, and they state, that:
> Typically, you don't need to run restore because it's called automatically by build.

That leads me to a question - have you tried to run described scenario or is it a generic question? :)

**Comment by BenjaminEngeset** [comment]
@kamil-mrzyglod Let me try to explain further, it was a rather bad description from me.

The contexts created and the context used for authentication does not work for the container, as it is running isolated. It is not inherited.

There must be a way we can perhaps use environment variables and get the running container to authenticate with the security principal that will make the `bicep build` work as expected.

Example that does not work since the container is running fully isolated:

```
- task: AzureCLI@2
    displayName: Cost forecasting
    inputs:
      azureSubscription: spn
      scriptType: bash 
      scriptLocation: inlineScript
      inlineScript: |
        docker run -e AZURE_CLIENT_ID=$(ClientId) -e AZURE_TENANT_ID=$(TenantId) -e AZURE_CLIENT_SECRET=$(Secret) -v $(pwd)/modules:/app/modules thecloudtheory/azure-cost-estimator:latest $(TestFilePath) $(SubscriptionId) $(ResourceGroupName)
```
