### ISSUE TITLE
Wiki correction for ADO Pipeline

### ISSUE THREAD

**Issue by riosengineer** [TheCloudTheory/arm-estimator#270]
Hey @kamil-mrzyglod :) Hope you are good!

The Wiki needs amending I think, as the later versions do not contain 'ace' in the name of the zip file.

https://github.com/TheCloudTheory/arm-estimator/wiki/Installation

```yaml
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        wget https://github.com/TheCloudTheory/arm-estimator/releases/download/1.5/linux-x64.zip
        unzip linux-x64.zip
        chmod +x ./azure-cost-estimator
      workingDirectory: $(System.DefaultWorkingDirectory)
```
